modLoader = "javafml"
loaderVersion = "[${forge_version_major},)"
license = "LGPL-3.0-only"

[[mods]]
 modId = "starlight"
 version = "${version}"
 displayName = "Starlight"
 authors = "Spottedleaf"
 description = '''
    Rewrites the light engine to fix lighting performance and lighting errors
 '''
 logoFile = "logo.png"
 displayURL = "https://www.curseforge.com/minecraft/mc-mods/starlight-forge"

 [[dependencies.starlight]]
  modId = "forge"
  mandatory = true
  versionRange = "[41.0.35,)"
  ordering = "NONE"
  side = "BOTH"

[[dependencies.starlight]]
  modId = "minecraft"
  mandatory = true
  versionRange = "[1.19, 1.20)"
  ordering = "NONE"
  side = "BOTH"